name: "opencv-build"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependency packages
        run: |
          sudo apt update 
          sudo apt install -y cmake git unzip wget zip
     
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Fetch opencv
        run: |
          git clone -b 4.5.4 --depth 1 https://github.com/opencv/opencv.git

      - name: Configuration cmake
        run: |
          mkdir opencv-release
          mkdir build
          cd build 
          
      - name: Build 
        run: |
          zip -q -r opencv-release.zip opencv-release

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: opencv-release
          path: opencv-release.zip

  release:
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v20
          release_name: Release
          draft: false
          prerelease: false
      
      - name: List
        run: |
          ls -al artifacts/opencv-release

      - name: Upload opencv
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/opencv-release/opencv-release.zip
          asset_name: opencv-release.zip
          asset_content_type: application/zip
