name: "opencv-build"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependency packages
        run: |
          sudo apt update 
          sudo apt install -y wget zip unzip build-essential cmake git pkg-config libgtk-3-dev \
          libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
          libxvidcore-dev libx264-dev libjpeg-dev libpng-dev libtiff-dev libwebp-dev\
          gfortran openexr libatlas-base-dev python3-dev python3-numpy \
          libtbb2 libtbb-dev libdc1394-22-dev libopenexr-dev \
          libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev
     
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create directory
        run: |
          mkdir build
          mkdir opencv-release

      - name: Fetch opencv
        run: |
          git clone -b 4.5.4 --depth 1 https://github.com/opencv/opencv.git
          git clone --depth 1 https://github.com/opencv/opencv_contrib.git

      - name: Configuration cmake
        working-directory: build
        run: |
          cmake -D CMAKE_BUILD_TYPE=RELEASE \
          -D CMAKE_INSTALL_PREFIX=../opencv-release \
          -D BUILD_SHARED_LIBS=OFF \
          -D BUILD_EXAMPLES=OFF \
          -D BUILD_TESTS=OFF \
          -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules \
          -D BUILD_PERF_TESTS=OFF ../opencv
          
      - name: Build
        working-directory: build
        run: |
          make -j$(nproc --all)
          make install

      - name: Zip
        run: |
          zip -q -r opencv-release.zip opencv-release

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: opencv-release
          path: opencv-release.zip

  release:
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v10
          release_name: Release
          draft: false
          prerelease: false

      - name: Upload opencv
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/opencv-release/opencv-release.zip
          asset_name: opencv-release.zip
          asset_content_type: application/zip
