name: "opencv-build"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependency packages
        run: |
          sudo apt update 
          sudo apt install -y wget zip unzip build-essential cmake git pkg-config
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

  build:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Create directory
        run: |
          mkdir build
          mkdir opencv-release

      - name: Fetch opencv
        run: |
          git clone -b 4.5.1 --depth 1 https://github.com/opencv/opencv.git

      - name: Configuration cmake
        working-directory: build
        run: |
          cmake -D CMAKE_BUILD_TYPE=RELEASE \
          -D CMAKE_INSTALL_PREFIX=../opencv-release \
          -D BUILD_SHARED_LIBS=OFF \
          -D BUILD_EXAMPLES=OFF \
          -D BUILD_TESTS=OFF \
          -D BUILD_ZLIB=ON \
          -D BUILD_PNG=ON \
          -D BUILD_JPEG=ON \
          -D BUILD_WEBP=ON \
          -D BUILD_TIFF=ON \
          -D BUILD_OPENJPEG=ON \
          -D BUILD_OPENEXR=ON \
          -D WITH_FFMPEG=OFF \
          -D WITH_V4L=OFF \
          -D WITH_1394=OFF \
          -D VIDEOIO_ENABLE_PLUGINS=OFF \
          -D WITH_GTK=OFF \
          -D HIGHGUI_ENABLE_PLUGINS=OFF \
          -D BUILD_PERF_TESTS=OFF ../opencv
          
      - name: Build
        working-directory: build
        run: |
          make -j$(nproc --all)
          make install

      - name: Zip
        run: |
          zip -q -r opencv-release.zip opencv-release

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: opencv-release
          path: opencv-release.zip

  # release:
  #   needs: [setup, build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download
  #       uses: actions/download-artifact@v2
  #       with:
  #         path: artifacts

  #     - name: Create release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: v13
  #         release_name: Release
  #         draft: false
  #         prerelease: false

  #     - name: Upload opencv
  #       uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ steps.create_release.outputs.upload_url }}
  #         asset_path: artifacts/opencv-release/opencv-release.zip
  #         asset_name: opencv-release.zip
  #         asset_content_type: application/zip
