name: "opencv-build"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependency packages
        run: |
          sudo apt update 
          sudo apt install -y cmake git unzip wget zip
     
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Fetch opencv
        run: |
          git clone -b 4.5.4 --depth 1 https://github.com/opencv/opencv.git ~/opencv-src

  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Configuration cmake
      #   run: |
      #     mkdir ~/build 
      #     cd ~/build 
      #     mkdir ~/opencv-release
      #     cmake -D CMAKE_BUILD_TYPE=RELEASE \
      #     -D CMAKE_INSTALL_PREFIX=~/opencv-release \
      #     -D BUILD_SHARED_LIBS=OFF \
      #     -D BUILD_EXAMPLES=OFF \
      #     -D BUILD_TESTS=OFF \
      #     -D BUILD_PERF_TESTS=OFF ~/opencv-src
          
      - name: Build 
        run: |
          # mkdir ~/build
          # cd ~/build
          pwd
          ls -al
          zip -q -r ~/opencv-release.zip ~/opencv-src

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: opencv-release.zip
          path: ~/opencv-release.zip

  release:
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v12
          release_name: Release
          draft: false
          prerelease: false
      
      - name: Upload opencv
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ~/opencv-release.zip
          asset_name: opencv-release.zip
          asset_content_type: application/zip
