name: "opencv-build"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependency packages
        run: |
          sudo apt update 
          sudo apt install -y cmake git unzip wget
          pwd 
          ls
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Fetch opencv
        run: |
          git clone --depth 1 https://github.com/opencv/opencv.git
          pwd
          echo $JAVA_HOME
          echo $ANT_HOME

      # - name: config
      #   run: |
      #     cmake -D CMAKE_BUILD_TYPE=RELEASE \
      #     -D CMAKE_INSTALL_PREFIX=~/opencv \
      #     -DBUILD_SHARED_LIBS=OFF \
      #     BUILD_EXAMPLES=OFF \
      #     BUILD_TESTS=OFF \
      #     BUILD_PERF_TESTS=OFF .. 